### ISSUE TITLE
Use better way to process and display title from shortcode output

### ISSUE THREAD

**Issue by hchouhan** [webtions/i-recommend-this#20]
Currently using `$return .= '<a href="' . esc_url($permalink) . '" title="' . esc_html($post_title) . '" rel="nofollow">' . esc_html($post_title) . '</a> ';`

This shows the HTML to the user unlike the title in a WordPress loop.

**Comment by FPCSJames** [comment]
This is mostly fine - in fact, you don't need to escape the permalink, as that's already sanitized by WP. However, for the title attribute, you should do:

`the_title_attribute(array('echo' => false, 'post' => $item->ID));`

See [this comment](https://developer.wordpress.org/reference/functions/get_the_title/#comment-1653). 

Otherwise what you're doing is very similar to what's done in the loop and given as example in the codex and dev docs.
